version: '3.8'
services:
  jenkins:
    env_file:
      - .env
    build:
      context: .
      args:
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"