jenkins:
  systemMessage: "Welcome to the Whanos Jenkins Instance."
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Whanos adminstrator"
            permissions:
              - "Overall/Administer"
            entries:
              - user: "admin"
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: "admin"
         name: "Admin"
         password: ${JENKINS_ADMIN_PASSWORD}

unclassified:
  location:
    url: http://server_ip:8080/

jobs:
  - file: /jenkins/job_dsl.groovy